module NetMiner
  module Mappings
    VIDEOGAME_PLATFORMS = Map.new(
      name: :videogame_platform,
      items: [
        { value: 'Amiga', aliases: ['amiga'] },
        { value: 'Amstrad CPC', aliases: ['amstrad cpc', 'cpc'] },
        { value: 'Android', aliases: ['android', 'google android'] },
        { value: 'Arcade', aliases: ['arcade'] },
        { value: 'Atari 2600', aliases: ['atari 2600', '2600'] },
        { value: 'Atari 5200', aliases: ['atari 5200', '5200'] },
        { value: 'Atari 7800', aliases: ['atari 7800', '7800'] },
        { value: 'Atari Lynx', aliases: ['atari lynx', 'lynx'] },
        { value: 'Philips CD-i', aliases: ['philips cd-i', 'cd-i', 'cdi'] },
        { value: 'Colecovision', aliases: ['colecovision'] },
        { value: 'Commodore 64', aliases: ['commodore 64', 'c64'] },
        { value: 'Sega Dreamcast', aliases: ['sega dreamcast', 'dreamcast', 'dc'] },
        { value: 'Nintendo Game Boy', aliases: ['nintendo game boy', 'game boy', 'gameboy', 'game boy classic'] },
        { value: 'Nintendo Game Boy Advance', aliases: ['nintendo game boy advance', 'gba', 'nintendo gba', 'gameboy advance', 'nintendo gameboy advance', 'game boy advance'] },
        { value: 'Nintendo Game Boy Color', aliases: ['nintendo game boy color', 'gbc', 'gb,nintendo gbc', 'gameboy color', 'nintendo gameboy color', 'game boy', 'game boy color'] },
        { value: 'Sega Game Gear', aliases: ['sega game gear', 'game gear', 'gamegear'] },
        { value: 'Nintendo GameCube', aliases: ['nintendo gamecube', 'gamecube', 'game cube', 'nintendo game cube', 'gc'] },
        { value: 'Sega Genesis', aliases: ['sega genesis', 'genesis'] },
        { value: 'Intellivision', aliases: ['intellivision'] },
        { value: 'Mac OS', aliases: ['mac os', 'mac', 'osx', 'macintosh', 'macos', 'apple'] },
        { value: 'NeoGeo', aliases: ['neogeo', 'neo geo', 'ng'] },
        { value: 'Neo Geo Pocket', aliases: ['neo geo pocket', 'neogeo pocket', 'np'] },
        { value: 'Neo Geo Pocket Color', aliases: ['neo geo pocket color', 'neogeo pocket color', 'npc'] },
        { value: 'Nintendo 3DS', aliases: ['nintendo 3ds', '3ds'] },
        { value: 'Nintendo 64', aliases: ['nintendo 64', 'n64'] },
        { value: 'Nintendo DS', aliases: ['nintendo ds', 'ds', 'dsi', 'nintendo dual screen'] },
        { value: 'Nintendo Entertainment System', aliases: ['Nintendo Entertainment System (NES)', 'nes', 'famicom'] },
        { value: 'Nintendo Switch', aliases: ['switch', 'nintendoswitch'] },
        { value: 'Magnavox Odyssey 2', aliases: ['magnavox odyssey 2', 'odyssey 2'] },
        { value: 'Ouya', aliases: ['ouya'] },
        { value: 'PC', aliases: ['pc', 'windows'] },
        { value: 'Sony Playstation', aliases: ['sony playstation', 'playstation', 'psx', 'ps1', 'playstation 1', 'psone'] },
        { value: 'Sony Playstation 2', aliases: ['sony playstation 2', 'playstation 2', 'ps2', 'sony ps2'] },
        { value: 'Sony Playstation 3', aliases: ['sony playstation 3', 'playstation 3', 'ps3', 'sony ps3'] },
        { value: 'Sony Playstation 4', aliases: ['sony playstation 4', 'playstation 4', 'ps4', 'sony ps4'] },
        { value: 'Sony Playstation Vita', aliases: ['sony playstation vita', 'playstation vita', 'vita', 'sony vita', 'ps vita', 'psv'] },
        { value: 'Sony PSP', aliases: ['sony psp', 'psp', 'playstation portable', 'sony playstation portable'] },
        { value: 'Sega 32X', aliases: ['sega 32x', '32x'] },
        { value: 'Sega CD', aliases: ['sega cd', 'scd'] },
        { value: 'Sega Master System', aliases: ['sega master system', 'master system'] },
        { value: 'Sega Saturn', aliases: ['sega saturn', 'saturn'] },
        { value: 'Super Nintendo Entertainment System', aliases: ['Super Nintendo (SNES)', 'super nintendo entertainment system', 'snes', 'super famicom', 'super nes'] },
        { value: '3DO', aliases: ['3do', 'threedo', '3d0'] },
        { value: 'TurboGrafx 16', aliases: ['turbografx 16', 'turbografx16', 'turbografx-16'] },
        { value: 'Nintendo Virtual Boy', aliases: ['nintendo virtual boy', 'virtual boy'] },
        { value: 'Nintendo Wii', aliases: ['nintendo wii', 'wii'] },
        { value: 'Nintendo Wii U', aliases: ['nintendo wii u', 'wii u', 'wiiu', 'wii-u'] },
        { value: 'WonderSwan', aliases: ['wonderswan', 'ws'] },
        { value: 'WonderSwan Color', aliases: ['wonderswan color', 'wsc'] },
        { value: 'Microsoft Xbox', aliases: ['microsoft xbox', 'xbox', 'xbox1'] },
        { value: 'Microsoft Xbox 360', aliases: ['microsoft xbox 360', 'xbox 360', 'xbox360', 'x360'] },
        { value: 'Microsoft Xbox One', aliases: ['microsoft xbox one', 'xbox one', 'xboxone', 'xbone'] }
      ]
    )
  end
end
